In [1]:
import pandas as pd
from zipline.pipeline import Pipeline
from zipline.pipeline.data import USEquityPricing
from sharadar.pipeline.factors import MarketCap
from sharadar.pipeline.factors import EV
from sharadar.pipeline.factors import Fundamentals
from sharadar.pipeline.engine import load_sharadar_bundle, symbol, symbols, make_pipeline_engine
from zipline.pipeline.filters import StaticAssets
import time
import datetime
from zipline.pipeline.factors import CustomFactor, DailyReturns, Returns

In [2]:
bundle = load_sharadar_bundle()

In [3]:
p = bundle.equity_daily_bar_reader

In [4]:
symbols(['IBM', 'F', 'AAPL'])

[Equity(199623 [IBM]), Equity(199713 [F]), Equity(199059 [AAPL])]

In [6]:
start_dt = pd.to_datetime('2020-02-03', utc=True)
end_dt = pd.to_datetime('2020-02-07', utc=True)
sids = [199713, 199623, 199059]
df = p.load_dataframe('close', start_dt, end_dt, sids)
df

[2020-06-17 20:40:29.600345] INFO: sharadar_db_bundle: Loading raw arrays for 3 assets (<class 'list'>).

                           199713  199623  199059
2020-02-03 00:00:00+00:00    8.98  146.27  308.66
2020-02-04 00:00:00+00:00    9.18  149.11  318.85
2020-02-05 00:00:00+00:00    8.31  156.33  321.45
2020-02-06 00:00:00+00:00    8.25  155.14  325.21
2020-02-07 00:00:00+00:00    8.11  153.41  320.03

In [7]:
start_dt = pd.to_datetime('2020-06-10', utc=True)
end_dt = pd.to_datetime('2021-02-07', utc=True)
sids = [199623, 199713, 199059]
df = p.load_dataframe('close', start_dt, end_dt, sids)
df

[2020-06-17 20:40:50.393429] INFO: sharadar_db_bundle: Loading raw arrays for 3 assets (<class 'list'>).

                           199623  199713  199059
2020-06-10 00:00:00+00:00  129.87    6.81  352.84
2020-06-11 00:00:00+00:00  118.01    6.13  335.90
2020-06-12 00:00:00+00:00  121.91    6.46  338.80
2020-06-15 00:00:00+00:00  121.65    6.50  342.99
2020-06-16 00:00:00+00:00  125.15    6.55  352.08
2020-06-17 00:00:00+00:00     NaN     NaN     NaN
2020-06-18 00:00:00+00:00     NaN     NaN     NaN
2020-06-19 00:00:00+00:00     NaN     NaN     NaN
2020-06-22 00:00:00+00:00     NaN     NaN     NaN
2020-06-23 00:00:00+00:00     NaN     NaN     NaN
2020-06-24 00:00:00+00:00     NaN     NaN     NaN
2020-06-25 00:00:00+00:00     NaN     NaN     NaN
2020-06-26 00:00:00+00:00     NaN     NaN     NaN
2020-06-29 00:00:00+00:00     NaN     NaN     NaN
2020-06-30 00:00:00+00:00     NaN     NaN     NaN
2020-07-01 00:00:00+00:00     NaN     NaN     NaN
2020-07-02 00:00:00+00:00     NaN     NaN     NaN
2020-07-06 00:00:00+00:00     NaN     NaN     NaN
2020-07-07 00:00:00+00:00     NaN     NaN     NaN
2020-07-08 00:00:00+00:00     NaN     NaN     NaN
2020-07-09 00:00:00+00:00     NaN     NaN     NaN
2020-07-10 00:00:00+00:00     NaN     NaN     NaN
2020-07-13 00:00:00+00:00     NaN     NaN     NaN
2020-07-14 00:00:00+00:00     NaN     NaN     NaN
2020-07-15 00:00:00+00:00     NaN     NaN     NaN
2020-07-16 00:00:00+00:00     NaN     NaN     NaN
2020-07-17 00:00:00+00:00     NaN     NaN     NaN
2020-07-20 00:00:00+00:00     NaN     NaN     NaN
2020-07-21 00:00:00+00:00     NaN     NaN     NaN
2020-07-22 00:00:00+00:00     NaN     NaN     NaN
...                           ...     ...     ...
2020-12-23 00:00:00+00:00     NaN     NaN     NaN
2020-12-24 00:00:00+00:00     NaN     NaN     NaN
2020-12-28 00:00:00+00:00     NaN     NaN     NaN
2020-12-29 00:00:00+00:00     NaN     NaN     NaN
2020-12-30 00:00:00+00:00     NaN     NaN     NaN
2020-12-31 00:00:00+00:00     NaN     NaN     NaN
2021-01-04 00:00:00+00:00     NaN     NaN     NaN
2021-01-05 00:00:00+00:00     NaN     NaN     NaN
2021-01-06 00:00:00+00:00     NaN     NaN     NaN
2021-01-07 00:00:00+00:00     NaN     NaN     NaN
2021-01-08 00:00:00+00:00     NaN     NaN     NaN
2021-01-11 00:00:00+00:00     NaN     NaN     NaN
2021-01-12 00:00:00+00:00     NaN     NaN     NaN
2021-01-13 00:00:00+00:00     NaN     NaN     NaN
2021-01-14 00:00:00+00:00     NaN     NaN     NaN
2021-01-15 00:00:00+00:00     NaN     NaN     NaN
2021-01-19 00:00:00+00:00     NaN     NaN     NaN
2021-01-20 00:00:00+00:00     NaN     NaN     NaN
2021-01-21 00:00:00+00:00     NaN     NaN     NaN
2021-01-22 00:00:00+00:00     NaN     NaN     NaN
2021-01-25 00:00:00+00:00     NaN     NaN     NaN
2021-01-26 00:00:00+00:00     NaN     NaN     NaN
2021-01-27 00:00:00+00:00     NaN     NaN     NaN
2021-01-28 00:00:00+00:00     NaN     NaN     NaN
2021-01-29 00:00:00+00:00     NaN     NaN     NaN
2021-02-01 00:00:00+00:00     NaN     NaN     NaN
2021-02-02 00:00:00+00:00     NaN     NaN     NaN
2021-02-03 00:00:00+00:00     NaN     NaN     NaN
2021-02-04 00:00:00+00:00     NaN     NaN     NaN
2021-02-05 00:00:00+00:00     NaN     NaN     NaN

[167 rows x 3 columns]

In [8]:
class ForwarsReturns(CustomFactor, BundleLoader):
    """
    Calculates the percent change in close price over the given window_length in the future.

    **Default Inputs**: [USEquityPricing.close]
    """
    inputs = []
    window_safe = True


    def compute(self, today, assets, out):
        self.bar_reader().trading_calendar.sessions_window(today, self)
        end_date = today  DateOffset(months=(window_length + 1) * 3)
        close = self.bar_reader().l
        out[:] = (close[-1] - close[0]) / close[0]

In [10]:
spe = make_pipeline_engine()

pipe_start = pd.to_datetime('2020-02-03', utc=True)
pipe_end = pd.to_datetime('2020-02-07', utc=True)


pipe = Pipeline(columns={
    'Close': USEquityPricing.close.latest,
    'monthly_ret': Returns(window_length=21)
    'monthly_fret': ForwarsReturns(window_length=21)
},
screen = StaticAssets(symbols(['IBM', 'F', 'AAPL']))
)

stocks = spe.run_pipeline(pipe, pipe_start, pipe_end)
stocks

[2020-06-17 20:42:31.164424] INFO: sharadar_db_bundle: Compute pipeline values in chunks of 120 days.
[2020-06-17 20:42:31.165266] INFO: sharadar_db_bundle: Compute values for pipeline from 2020-02-03 to 2020-02-07.
[2020-06-17 20:42:31.636384] INFO: sharadar_db_bundle: Computing term 1 of 5 [AssetExists()]
[2020-06-17 20:42:31.637350] INFO: sharadar_db_bundle: Term already in workspace: no computation needed
[2020-06-17 20:42:31.638773] INFO: sharadar_db_bundle: Computing term 2 of 5 [StaticAssets([], 0)]
[2020-06-17 20:42:31.640290] INFO: sharadar_db_bundle: Elapsed time: 0:00:00.001566
[2020-06-17 20:42:31.641159] INFO: sharadar_db_bundle: Computing term 3 of 5 [USEquityPricing.close::float64]
[2020-06-17 20:42:31.643728] INFO: sharadar_db_bundle: Loading raw arrays for 9824 assets (<class 'pandas.core.indexes.numeric.Int64Index'>).
[2020-06-17 20:42:32.132573] INFO: sharadar_db_bundle: Elapsed time: 0:00:00.491443
[2020-06-17 20:42:32.133547] INFO: sharadar_db_bundle: Computing term 4 of 5 [Latest([USEquityPricing.close], 1)]
[2020-06-17 20:42:32.135936] INFO: sharadar_db_bundle: Elapsed time: 0:00:00.002409
[2020-06-17 20:42:32.136701] INFO: sharadar_db_bundle: Computing term 5 of 5 [Returns([USEquityPricing.close], 21)]
[2020-06-17 20:42:32.142308] INFO: sharadar_db_bundle: Elapsed time: 0:00:00.005608

                                                  Close  monthly_ret
2020-02-03 00:00:00+00:00 Equity(199059 [AAPL])  309.51     0.030498
                          Equity(199623 [IBM])   143.73     0.061365
                          Equity(199713 [F])       8.82    -0.063694
2020-02-04 00:00:00+00:00 Equity(199059 [AAPL])  308.66     0.037757
                          Equity(199623 [IBM])   146.27     0.088805
                          Equity(199713 [F])       8.98    -0.024973
2020-02-05 00:00:00+00:00 Equity(199059 [AAPL])  318.85     0.063542
                          Equity(199623 [IBM])   149.11     0.111931
                          Equity(199713 [F])       9.18     0.002183
2020-02-06 00:00:00+00:00 Equity(199059 [AAPL])  321.45     0.077281
                          Equity(199623 [IBM])   156.33     0.164990
                          Equity(199713 [F])       8.31    -0.101622
2020-02-07 00:00:00+00:00 Equity(199059 [AAPL])  325.21     0.072628
                          Equity(199623 [IBM])   155.14     0.146552
                          Equity(199713 [F])       8.25    -0.108108